version: '3.8'

services:

  nginx:
    build: ./_build/nginx
    depends_on:
      - front
      - back
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./_build/nginx/certs:/certs
    networks:
      - netpong

  front:
    build: ./_build/front
    volumes:
      - ./front:/app
    networks:
      - netpong
    working_dir: /app

  back:
    build: ./_build/back
    depends_on:
      - mariadb
    volumes:
      - ./api:/app
    networks:
      - netpong
    env_file:
      - .env
    working_dir: /app

  mariadb:
    image: mariadb
    volumes:
      - pong_db:/var/lib/mysql/
    networks:
      - netpong
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_ROOT_HOST: ${MARIADB_ROOT_HOST}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}

networks:
  netpong:

volumes:
  pong_db: