version: '3.8'

services:

  nginx:
    build: ./_build/nginx
    depends_on:
      - front
      - back
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./_build/nginx/certs:/certs
    networks:
      - netpong

  front:
    build: ./_build/front
    volumes:
      - ./front:/app
    networks:
      - netpong
    working_dir: /app

  back:
    build: ./_build/back
    depends_on:
      - mariadb
    volumes:
      - ./api:/app
    networks:
      - netpong
    environment:
      DATABASE_USER: ${DB_USERNAME}
      DATABASE_PASSWORD: ${DB_PASSWORD}
      DATABASE_DB: ${DB_DB}
      MAIL_USER: ${MAIL_USER}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      REDIRECT_URI: ${REDIRECT_URI}
      REFRESH_TOKEN: ${REFRESH_TOKEN}
    working_dir: /app

  mariadb:
    image: mariadb
    volumes:
      - pong_db:/var/lib/mysql/
    networks:
      - netpong
    environment:
      MARIADB_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MARIADB_ROOT_HOST: ${ROOT_HOST}
      MARIADB_DATABASE: ${DB_DB}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}

networks:
  netpong:

volumes:
  pong_db: